version: '1'

services:
  database:
    image: postgres:latest
    restart: on-failure
    container_name: postgres
    hostname: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=weaforetracam
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=weaforetracampass
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
  cache:
    hostname: redis
    image: redis:latest
    restart: on-failure
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .docker.env
    depends_on:
      - database
      - cache
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  pg_data:
    driver: local
  rabbit_data:
    driver: local
  mongo_data:
    driver: local
