import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migrations1705160467197 implements MigrationInterface {
  name = 'Migrations1705160467197';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "location-search-history" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" character varying(300), "last_updated" TIMESTAMP WITH TIME ZONE DEFAULT now(), "last_updated_by" character varying(300), "deleted_date" TIMESTAMP WITH TIME ZONE, "date_time" TIMESTAMP WITH TIME ZONE NOT NULL, "location" character varying(300) NOT NULL, CONSTRAINT "PK_52156933e84f1cabfaafb23bb9f" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "location-search-history"`);
  }
}
